# -*- coding: utf-8 -*-
"""HistorialCoca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rE3zuZCmXEXCiDsAk9KRWU-0pjES5df7
"""

#Se importan las librerias
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

#Inicia sesión de spark
spark = SparkSession.builder.appName('AnalisisCoca').getOrCreate()

#Se crea el df
df = spark.read.csv('hdfs://namenode:8020/user/hadoop/hist_coca.csv', header=True, inferSchema=True)

#Se muestran los primeros 10 registros
df.show(10)

#Se imprime el schema para entender los tipos de variables
df.printSchema()

#Se consultan las tiendas registradas en el df
df.select('Tienda').distinct().show()

#Se consultan los productos registrados en el df
df.select('Producto').distinct().show()

#Se crea un df agrupado por los productos e indique el número de unidades vendidas y los ingresos de cada uno
#Se convierte a pandas para facilitar crear las gráficas
ventasProducto = df.groupBy('Producto').agg(sum('Cantidad').alias('Unidades Totales'), round(sum('Total'),2).alias('Ingresos Totales')).orderBy(desc('Unidades Totales')).toPandas()
ventasProducto

#Se crea gráfica de barra para visualizar los productos más vendidos por volúmen
plt.figure(figsize=(11,6))
sns.barplot(x='Producto', y='Unidades Totales', data = ventasProducto, palette='magma')
plt.title('Ventas Totales por Producto')
plt.show()

#Se crea gráfica de pay para saber qué productos han generado más ingresos
plt.figure(figsize=(11,6))
plt.pie(ventasProducto['Ingresos Totales'], labels=ventasProducto['Producto'], autopct='%1.1f%%', colors = sns.color_palette('Spectral'))
plt.title('Ingresos Totales por Producto')
plt.show()

#Se crea un df agrupado por las tiendas e indique el número de unidades vendidas y los ingresos de cada uno
#Se convierte a pandas para facilitar crear las gráficas
ventasTienda = df.groupBy('Tienda').agg(sum('Cantidad').alias('Unidades Totales'), round(sum('Total'),2).alias('Ingresos Totales')).orderBy(desc('Unidades Totales')).toPandas()
ventasTienda

#Se crea gráfica para visualizar las tiendas con mayor venta
sns.barplot(x='Unidades Totales', y='Tienda', data = ventasTienda, palette='icefire')
plt.title('Ventas Totales por Tienda')
plt.show()

#Se crea gráfica para saber qué tienda ha generado más ingresos
sns.barplot(x='Tienda', y='Ingresos Totales', data = ventasTienda, palette='mako')
plt.title('Ingresos Totales por Tienda')
plt.show()

"""Los productos más populares son la Coca Cola Original, Sin Azucar, y Cherry. Y los productos que han generado más ingresos son la Cherry, Energy, y Original. Y se identificó que Bodega Aurrera es la tienda que ha registrado más ventas, y por tanto, mayor capital. También se puede notar que Oxxo y 7-Eleven estan casi empatados por el segundo lugar, lo que significa que existe un fuerte mercado en las tiendas de conveniencia.

Por lo que se recomienda aumentar la distribución de Coca Cola Cherry en Bodega Aurrera. Lanzar promociones en Oxxo y 7-Eleven para la Coca Cola Sin Azúcar.
Debido a la baja venta de Coca Cola Light, se recomienda disminuir la producción con el objetivo de disminuir gastos operativos.
"""