# -*- coding: utf-8 -*-
"""InteraccionUsuarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdKIGlqZHt2y7wPClcgM2MQTv8hvZPB3
"""

#Se importan las librerias
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

#Se inicia sesion de spark
spark = SparkSession.builder.appName('UsuarioWeb').getOrCreate()

#Se crea el df
df = spark.read.json('hdfs://namenode:8020/user/hadoop/usuarios_web.json', multiLine=True)

df.printSchema()

#Se calcula el promedio de duracion de sesion por pais
df.groupBy('pais').agg(avg('duracion_sesion').alias('promedio duracion')).orderBy('promedio duracion', ascending=False).show()

#Se calcula el promedio de duracion de sesion por dispositivo
df.groupBy('dispositivo').agg(avg('duracion_sesion').alias('promedio duracion')).orderBy('promedio duracion', ascending=False).show()

#Se calcula el promedio de paginas vistas por dispositivo
df.groupBy('dispositivo').agg(avg('paginas_vistas').alias('promedio paginas vistas')).orderBy('promedio paginas vistas', ascending=False).show()

#Se crea un df solo con los usuarios convertidos y se calcula el promedio de duracion de sesion y paginas vistas
conv = df.filter(col('conversion') == True)
conv.select(avg('duracion_sesion').alias('promedio duracion sesion'), avg('paginas_vistas').alias('promedio paginas vistas')).show()

#De los usuarios convertidos se agrupan por pais
conv.groupBy("pais").count().orderBy("count", ascending=False).show()

#Se agrupa por referencia los usuarios convertidos
conv.groupBy("referencia").count().orderBy("count", ascending=False).show()

"""La tasa de fuente de tráfico que genera más conversiones son los Anuncios y Orgánico.
Aunque México cuenta con el menor tiempo promedio de duración de sesión, empata con Canadá por el país con más conversiones. Esto indica que la población de México es más susceptible a realizar alguna acción dentro de la página web.
Con esta información se podría tomar el territorio mexicano como un buen lugar para probar campañas publicitarias antes de sacarles globalmente.
"""

