# -*- coding: utf-8 -*-
"""VentaElectronicos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQoA2h3Q7AzkZ5hQxPkVUCIQtJoW3_Sy

El objetivo es introducir nuevos productos que tengan una buena posibilidad de ser disruptivos en una cadena de tiendas de tecnología. Para eso se quiere analizar el rendimiento actual de los productos vendidos.
"""

#Se importan librerias
import xml.etree.ElementTree as ET
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Se parsea el xml
tree = ET.parse('ventas_electronicos.xml')
root = tree.getroot()

#Se extraen los datos a lista
data = []
for ingreso in root.findall(".//Venta"):
    record = {
        "VentaID": ingreso.find("VentaID").text,
        "Fecha": ingreso.find("Fecha").text,
        "Tienda": ingreso.find("Tienda").text,
        "Producto": ingreso.find("Producto").text,
        "Categoria": ingreso.find("Categoria").text,
        "Precio": ingreso.find("Precio").text,
        "Cantidad": ingreso.find("Cantidad").text,
        "Total": ingreso.find("Total").text
    }
    data.append(record)

#Se convierte la lista a df
df = pd.DataFrame(data)

df.info()

df.head()

#Se convierte columnas con datos numericos a tipo correcto
df['VentaID'] = pd.to_numeric(df['VentaID'].astype('Int64'))
df['Fecha'] = pd.to_datetime(df['Fecha'])
df['Precio'] = pd.to_numeric(df['Precio'])
df['Cantidad'] = pd.to_numeric(df['Cantidad'].astype('Int64'))
df['Total'] = pd.to_numeric(df['Total'])

df.info()

#Se identifica la variedad de productos por categoría
df['Categoria'].value_counts().sort_values(ascending=False)

#Se calcula el precio promedio por cada categoría
df.groupby('Categoria')['Precio'].mean().sort_values(ascending=False)

#Se calcula el porcentaje de ventas por categoría
ventas_cat = df.groupby('Categoria')['Total'].sum()
total_ventas = df['Total'].sum()
porc_cat = (ventas_cat / total_ventas)*100
print(porc_cat)

porc_cat.sort_values().plot(kind='barh', color='cadetblue')
plt.title('Porcentaje de ventas por Categoria')
plt.xlabel('%')

La fotografía es la categoría lider en volumen y ventas, lo que nos indica una demanda constante que ha
sido satisfecha por la variedad de productos que se venden.
La baja cantidad de ventas en Tablets  podría indicar una oportunidad para un producto disruptivo que redefina
el uso de las tablets, quizás enfocándose en nichos específicos (educación, productividad móvil especializada) o integrándolas de formas novedosas con otros dispositivos.