# -*- coding: utf-8 -*-
"""Youtube2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZZSEfJFfIqqPlZr_scg7a3Kq3H-shbS
"""

Una agencia de publicidad quiere identificar los territorios en los que Youtube ha tenido mayor penetración, y también aquellos países que muestran promesa en crecer el número de usuarios. Todo esto con el objetivo de identificar nuevos mercados.

#Se importan las librerias
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

#Se inicia sesion de spark
spark = SparkSession.builder.appName('Youtube').getOrCreate()

#Se crea el df
df = spark.read.json('hdfs://namenode:8020/user/hadoop/youtube2025.json', multiLine=True)

df.printSchema()

df.show()

pdf = df.toPandas()

pdf.head()

#Se muestra los 5 paises con mayor numero de usuarios registrados desde Febrero 2024
tot_usuarios = pdf.sort_values(by='YouTubeUsers_TotalUsers_Num_2024Feb', ascending=False)
print(tot_usuarios[['country', 'YouTubeUsers_TotalUsers_Num_2024Feb']].head())

#De esos 5 paises, se calcula la penetracion
top_5 = pdf.sort_values(by='YouTubeUsers_TotalUsers_Num_2024Feb', ascending=False).head()
print(top_5[['country', 'YouTubeUsers_Penetration_Pct_2024Feb']])

"""Aunque India es el país con el mayor número de usuarios, se ha registrado mayor penetración en México.
En el caso de India, la agencia de publicidad se debe enfocar en crear campañas que busquen adquirir nuevos usuarios, ya sea por utilizando referencias culturales que sean relevantes al público general. Y para México, la mayor penetración significa que Youtube es una plataforma muy influyente y con un alcance significativo.
Por lo que México es un territorio idoneo para las empresas a presentar nuevos productos que no hayan sacado en otros mercados.
"""

#Se calcula el número de usuarios en julio de 2023
pdf['YouTubeUsersJuly2023_Num'] = pdf['YouTubeUsersJuly2023'] * 1000000

#Se calcula el crecimiento de usuarios
pdf['UserGrowth'] = pdf['YouTubeUsers_TotalUsers_Num_2024Feb'] - pdf['YouTubeUsersJuly2023_Num']

#Se calcula el crecimiento relativo (en porcentaje)
pdf['GrowthPercentage'] = (pdf['UserGrowth'] / pdf['YouTubeUsersJuly2023_Num']) * 100

#Se ordena por crecimiento absoluto para ver los mercados con mayor aumento en número de usuarios
crec_abs = pdf.sort_values(by='UserGrowth', ascending=False)

#Se ordena por crecimiento relativo para ver los mercados con mayor aumento porcentual
aumento = pdf.sort_values(by='GrowthPercentage', ascending=False)

# Gráfico de crecimiento absoluto
sns.barplot(x='country', y='UserGrowth', data=crec_abs.head(10), palette='viridis')
plt.title('10 Mercados por Crecimiento Absoluto de Usuarios (Jul 2023 - Feb 2024)')
plt.xlabel('País')
plt.ylabel('Crecimiento de Usuarios')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Gráfico de crecimiento porcentual
sns.barplot(x='country', y='GrowthPercentage', data=aumento.head(10), palette='mako')
plt.title('Top 10 Mercados por Crecimiento Porcentual de Usuarios (Jul 2023 - Feb 2024)')
plt.xlabel('País')
plt.ylabel('Crecimiento Porcentual (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Puerto Rico, Kenia y Sri Lanka lideraron en términos de la mayor proporción de crecimiento de su base de usuarios, sugiriendo una rápida adopción relativa en estos mercados. Ya que estos territorios son "virgenes", es importante establecer temprano una marca mientras que la base de usuarios sigue expandiéndose."""